public enum SoundType
{
    environment,
    doorOpenGlass,
    doorClosedGlass,
    doorOpenWood,
    doorClosedWood,
    dialogOptionSelection,
    dialogForward,
    dialogSelectedOption,
    uiHover,
    Act1BackgroundMusic,
    Act2BackgroundMusic,
    MainMenuBackgroundMusic,
    EnviromentBackgroundMusic,
    OpenNote,
    TVOn,
    TvOff
}
